import Head from "next/head";
import styles from "../styles/Contact.module.css";

// Components
import Navbar from "../components/Navbar";


export default function Contact() {
    const { container, main } = styles;

    return (
        <div className={container}>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <main className={main}>
                <h2><span>Phone</span>079 814 7004</h2>
                <h2><span>Email</span>monyaketoo@gmail.com</h2>
                <h2><span>Linkedin</span>https://www.linkedin.com/in/kutlwisiso-monyake-19a09b233</h2>
            </main>
        </div>
    )
}