import Head from "next/head";
import styles from "../styles/Home.module.css";

// Components
import Navbar from "../components/Navbar";


export default function Home() {
  const { container, main, leftSide, rightSide } = styles;

  return (
    <div className={container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className={main}>
        <div className={leftSide}>
          <img src="/image1.jpg" alt="" />
        </div>
        <div className={rightSide}>
          <h1>Kutlwisiso Monyake</h1>
          <h3>web developer</h3>
        </div>
      </main>
    </div>
  )
}
