import Head from "next/head";

// Styles
import { Container } from "../styled/index.styled";


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Kutlwisiso Monyake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Bangers&family=Roboto+Condensed&display=swap" rel="stylesheet"/>
      </Head>

      <Container onScrollCapture={(e) => console.log(e.target)}>
        <nav className="navbar">
          <a href="#home"><h3>Home</h3></a>
          <a href="#about"> <h3>About</h3></a>
          <a href="#projects"><h3>Projects</h3></a>
          <a href="#contact"><h3>Contact</h3></a>
        </nav>

        <div id="home" className="home-container">
          <div className="img-container">
            <img src="/image1.jpg" alt="hero-img" />
          </div>
          <div className="right-side">
            <h1>Kutlwisiso Monyake</h1>
            <p>Full-Stack Web Developer</p>
          </div>
        </div>

        <div id="about" className="about-container">
          <h2>About</h2>
          <p>
            Hello, my name is Kutlwisiso.<br/>
            I have been writing code for quite some time now.<br/>
            Programming started as a hobby for me but I began to take is seriously as I gained some serious skills.
          </p>
          <br/>
          <p>I decided to sign up for a bootcamp in order to take my skills to the next level.</p>
          <p>
            I understand that I still have a long way to go but thats ok because I know im built to overcome any challenges that lie ahead.
          </p>
          <h2>Skills</h2>
          <ul>
            <li>HTML</li>
            <li>CSS</li>
            <li>Javascript</li>
            <li>NodeJS</li>
            <li>ReactJS</li>
            <li>Firebase</li>
            <li>Mongodb</li>
            <li>NextJS</li>
            <li>React native</li>
          </ul>
          <h2>Education</h2>
          <p>Graduated at HyperionDev with a <span>99%</span> grade average.</p>
        </div>

        <div id="projects" className="projects-container">
          <h1>Projects</h1>
          <ul>
            <li><span>Memory game</span><br />https://memory-game-01.herokuapp.com/</li>
            <li><span>Netflix clone</span><br/>https://github.com/KMonyake/Netfilx_Clone</li>
            <li><span>Tiktok clone</span><br />https://github.com/KMonyake/TikTok_Clone</li>
            <li><span>Online shop</span><br />https://github.com/KMonyake/comfy-store</li>
            <li><span>Chat app</span><br />https://chatapp-002.netlify.app/</li>
          </ul>
        </div>

        <div id="contact" className="contact-container">
          <h1>Contact</h1>
          <div className="contact-details-container">
            <h2><span>Phone: </span>079 814 7004</h2>
            <h2><span>Email: </span>monyaketoo@gmail.com</h2>
            <h2><span>Linkedin: </span>https://www.linkedin.com/in/kutlwisiso-monyake-19a09b233</h2>
          </div>
        </div>
      </Container>
    </>
  )
}
